FROM bwoa0001/gifdroid:latest

# to build docker: docker build -t gifdroidall .
# to docker run this: docker run -it --add-host=host.docker.internal:host-gateway  gifdroidall
# To connect to emulator: adb connect host.docker.internal:5555


